version: '3.8'

services:
  server:
    build: ./backend
    volumes:
      - ./backend:/myback
    depends_on:
      - database
    links:
      - database
    ports:
      - 3001:3001
    command: [ "npm", "start" ]

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/appfront
    depends_on:
      - database
      - server
    links:
      - database
      - server
    ports:
      - 3000:3000
